// Flat ESLint config for the Blockparty workspace.
//
// The dependency-direction rules below are normative, not advisory.
// See ENG-002 in docs/engineering/architecture.md.

import js from "@eslint/js";
import tseslint from "typescript-eslint";
import nextPlugin from "@next/eslint-plugin-next";
import reactHooks from "eslint-plugin-react-hooks";
import globals from "globals";

/** Modules a browser bundle must never pull in. */
const SERVER_ONLY_MODULES = [
  {
    name: "mongodb",
    message: "Browser code must not import the MongoDB driver. See ENG-002.",
  },
  {
    name: "@blockparty/game-engine",
    message:
      "Only apps/web server modules call the engine to accept a command. See ENG-002.",
  },
];

/** Modules the pure engine must never pull in. */
const IMPURE_MODULES = [
  { name: "mongodb", message: "packages/game-engine is pure. See ENG-020." },
  { name: "next", message: "packages/game-engine is pure. See ENG-020." },
  { name: "react", message: "packages/game-engine is pure. See ENG-020." },
  { name: "server-only", message: "packages/game-engine is pure. See ENG-020." },
];

export default tseslint.config(
  {
    ignores: [
      "**/.next/**",
      "**/dist/**",
      "**/node_modules/**",
      "**/*.tsbuildinfo",
      // Generated by Next.js. Not ours to lint.
      "**/next-env.d.ts",
    ],
  },

  js.configs.recommended,
  ...tseslint.configs.recommended,

  // Next.js and React Hooks rules apply to the app only. Using the plugins
  // directly avoids the legacy eslint-config-next compatibility patch.
  {
    files: ["apps/web/**/*.{ts,tsx}"],
    languageOptions: {
      globals: { ...globals.browser, ...globals.node },
    },
    settings: { next: { rootDir: "apps/web" } },
    plugins: { "@next/next": nextPlugin, "react-hooks": reactHooks },
    rules: {
      ...nextPlugin.configs.recommended.rules,
      ...nextPlugin.configs["core-web-vitals"].rules,
      ...reactHooks.configs.recommended.rules,
    },
  },

  {
    rules: {
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
      "@typescript-eslint/consistent-type-imports": "error",
    },
  },

  // ---------------------------------------------------------------------
  // Browser code must not reach server modules, the database, or the engine.
  // The `server-only` import inside src/server/** is the hard guard; this
  // rule catches the mistake earlier and explains why.
  // ---------------------------------------------------------------------
  {
    files: ["apps/web/src/client/**/*.{ts,tsx}", "apps/web/src/components/**/*.{ts,tsx}"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          paths: SERVER_ONLY_MODULES,
          patterns: [
            {
              group: ["@/server", "@/server/*", "**/server/*"],
              message:
                "Browser code must not import apps/web server modules. See ENG-002.",
            },
          ],
        },
      ],
    },
  },

  // ---------------------------------------------------------------------
  // The engine is a pure reducer: no IO, no clock, no randomness, no
  // transport, no framework. See ENG-020.
  // ---------------------------------------------------------------------
  {
    files: ["packages/game-engine/**/*.ts"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          paths: IMPURE_MODULES,
          patterns: [
            {
              group: ["node:*", "fs", "path", "crypto", "http", "https"],
              message: "packages/game-engine must not use Node APIs. See ENG-020.",
            },
          ],
        },
      ],
      "no-restricted-globals": [
        "error",
        { name: "Date", message: "The engine reads no clock. See ENG-020." },
      ],
      "no-restricted-properties": [
        "error",
        {
          object: "Math",
          property: "random",
          message: "The engine uses the seeded PRNG only. See ENG-022.",
        },
      ],
    },
  },

  // ---------------------------------------------------------------------
  // contracts depends on Zod alone. See ENG-002.
  // ---------------------------------------------------------------------
  {
    files: ["packages/contracts/**/*.ts"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          paths: [
            { name: "react", message: "packages/contracts depends on Zod only." },
            { name: "next", message: "packages/contracts depends on Zod only." },
            { name: "mongodb", message: "packages/contracts depends on Zod only." },
            {
              name: "@blockparty/game-engine",
              message: "packages/contracts depends on Zod only.",
            },
          ],
        },
      ],
    },
  },
);
